version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=@Neverdie1001
    command: "start-notebook.sh --NotebookApp.token='@Neverdie1001'"